// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM6Jvbt9dn7cwFCvfb7qThDBSUL-wzwbE',
    appId: '1:254828299957:web:a7c1dc13b2f776f3f7e0fc',
    messagingSenderId: '254828299957',
    projectId: 'controle-abastecimento-f1309',
    authDomain: 'controle-abastecimento-f1309.firebaseapp.com',
    storageBucket: 'controle-abastecimento-f1309.firebasestorage.app',
    measurementId: 'G-HDDQVJR7KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsZzQMsF-vTgQucGebu3RynTILMEfseNk',
    appId: '1:254828299957:android:cbabb8e77805e2eef7e0fc',
    messagingSenderId: '254828299957',
    projectId: 'controle-abastecimento-f1309',
    storageBucket: 'controle-abastecimento-f1309.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkYnCWvbGlHqyXJWaxAMJPBfPagm75r-U',
    appId: '1:254828299957:ios:e716c0dabc6f189ff7e0fc',
    messagingSenderId: '254828299957',
    projectId: 'controle-abastecimento-f1309',
    storageBucket: 'controle-abastecimento-f1309.firebasestorage.app',
    iosBundleId: 'com.example.abastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkYnCWvbGlHqyXJWaxAMJPBfPagm75r-U',
    appId: '1:254828299957:ios:e716c0dabc6f189ff7e0fc',
    messagingSenderId: '254828299957',
    projectId: 'controle-abastecimento-f1309',
    storageBucket: 'controle-abastecimento-f1309.firebasestorage.app',
    iosBundleId: 'com.example.abastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM6Jvbt9dn7cwFCvfb7qThDBSUL-wzwbE',
    appId: '1:254828299957:web:072bf3e039600ceef7e0fc',
    messagingSenderId: '254828299957',
    projectId: 'controle-abastecimento-f1309',
    authDomain: 'controle-abastecimento-f1309.firebaseapp.com',
    storageBucket: 'controle-abastecimento-f1309.firebasestorage.app',
    measurementId: 'G-VST22RQGD6',
  );
}
